ALTER TABLE INVITACION_SOCIEDAD 
ALTER COLUMN estadoInvitacion_inviSoc SMALLINT

ALTER TABLE INVITACION_SOCIEDAD
ADD usuarioInserta_inviSoc VARCHAR(50)

ALTER TABLE INVITACION_SOCIEDAD
ADD fechaInserta_inviSoc DATETIME

ALTER TABLE INVITACION_SOCIEDAD
ADD usuarioModifica_inviSoc VARCHAR(50)

ALTER TABLE INVITACION_SOCIEDAD
ADD fechaModifica_inviSoc DATETIME

ALTER TABLE INVITACION_SOCIEDAD
ADD usuarioElimina_inviSoc VARCHAR(50)

ALTER TABLE INVITACION_SOCIEDAD
ADD fechaElimina_inviSoc DATETIME